<p>Static Text</p>
<?php
echo "<p>This text was generated by PHP</p>";
$variable = "word";

echo 'This single quote string uses a $variable </br>';
echo "This double quotes echo string uses a $variable";





?>
<p>This text was not.</p>